import { Product, Batch, Sale, SaleItem, AuditLog, StoreSettings } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  id: 'default-settings',
  tenantId: 'demo-tenant-pharmpulse',
  storeName: 'AuraCare Pharmacy & Healthcare',
  tagline: 'Trusted Community Healthcare & Dispensary',
  address: 'Plot 44, Kenyatta Avenue, Central District',
  phone: '+255 784 920 110',
  email: 'dispensary@auracarepharm.com',
  tinNumber: 'TIN-114-889-402',
  currencySymbol: 'TSh',
  currencyCode: 'TZS',
  taxRate: 0, // Most pharmaceuticals are VAT exempt, configurable in settings
  taxInclusive: true,
  enableSoundBeeps: true,
  currentAttendant: 'Pharm. David Ndunguru',
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Augmentin 625mg',
    genericName: 'Amoxicillin + Clavulanic Acid',
    sku: 'AUG-625',
    barcode: '5010724521014',
    category: 'Antibiotics',
    dosageForm: 'tablets',
    packSize: 14,
    unitName: 'Tablet',
    reorderThreshold: 10,
    buyingPrice: 18000,
    sellingPrice: 26000,
    unitSellingPrice: 2000,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Broad-spectrum beta-lactam antibacterial for respiratory and soft tissue infections.',
    synced: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Panadol Extra 500mg/65mg',
    genericName: 'Paracetamol + Caffeine',
    sku: 'PAN-EXT-500',
    barcode: '5000347070101',
    category: 'Analgesics & Antipyretics',
    dosageForm: 'tablets',
    packSize: 100,
    unitName: 'Tablet',
    reorderThreshold: 15,
    buyingPrice: 15000,
    sellingPrice: 22000,
    unitSellingPrice: 300,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Fast-acting relief from headaches, migraines, backache, and toothache.',
    synced: true,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Coartem 20/120mg (6x4)',
    genericName: 'Artemether + Lumefantrine',
    sku: 'COA-20120',
    barcode: '7611355001124',
    category: 'Antimalarials',
    dosageForm: 'tablets',
    packSize: 24,
    unitName: 'Tablet',
    reorderThreshold: 20,
    buyingPrice: 8500,
    sellingPrice: 13500,
    unitSellingPrice: 600,
    isPom: true,
    requiresStorageWarning: false,
    description: 'First-line ACT combination therapy for acute uncomplicated Plasmodium falciparum malaria.',
    synced: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Azithromycin 500mg',
    genericName: 'Azithromycin Dihydrate',
    sku: 'AZI-500',
    barcode: '8901117182903',
    category: 'Antibiotics',
    dosageForm: 'capsules',
    packSize: 3,
    unitName: 'Capsule',
    reorderThreshold: 12,
    buyingPrice: 4500,
    sellingPrice: 7500,
    unitSellingPrice: 2800,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Macrolide antibiotic 3-day course for upper and lower respiratory tract infections.',
    synced: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Metformin HCl 500mg',
    genericName: 'Metformin Hydrochloride',
    sku: 'MET-500',
    barcode: '5012345678901',
    category: 'Diabetes & Endocrine',
    dosageForm: 'tablets',
    packSize: 100,
    unitName: 'Tablet',
    reorderThreshold: 10,
    buyingPrice: 7000,
    sellingPrice: 12000,
    unitSellingPrice: 150,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Biguanide antihyperglycemic oral medicine for Type 2 Diabetes Mellitus management.',
    synced: true,
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-006',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Amlodipine Besylate 10mg',
    genericName: 'Amlodipine',
    sku: 'AML-10',
    barcode: '8902223334445',
    category: 'Cardiovascular',
    dosageForm: 'tablets',
    packSize: 30,
    unitName: 'Tablet',
    reorderThreshold: 8,
    buyingPrice: 5000,
    sellingPrice: 8500,
    unitSellingPrice: 350,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Dihydropyridine calcium channel blocker for systemic hypertension and angina.',
    synced: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Cataflam 50mg',
    genericName: 'Diclofenac Potassium',
    sku: 'CAT-50',
    barcode: '7680456123456',
    category: 'Analgesics & Antipyretics',
    dosageForm: 'tablets',
    packSize: 20,
    unitName: 'Tablet',
    reorderThreshold: 12,
    buyingPrice: 9000,
    sellingPrice: 14000,
    unitSellingPrice: 800,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Fast onset NSAID for acute pain, post-traumatic inflammation, and dysmenorrhea.',
    synced: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Ventolin Inhaler 100mcg',
    genericName: 'Salbutamol Sulfate',
    sku: 'VEN-INH-100',
    barcode: '5000456789123',
    category: 'Respiratory',
    dosageForm: 'inhaler',
    packSize: 1,
    unitName: 'Canister (200 doses)',
    reorderThreshold: 5,
    buyingPrice: 11000,
    sellingPrice: 16500,
    unitSellingPrice: 16500,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Short-acting beta-2 adrenergic receptor agonist for acute bronchospasm and asthma relief.',
    synced: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole Delayed-Release',
    sku: 'OME-20',
    barcode: '8903334445556',
    category: 'Gastrointestinal',
    dosageForm: 'capsules',
    packSize: 28,
    unitName: 'Capsule',
    reorderThreshold: 10,
    buyingPrice: 4000,
    sellingPrice: 7000,
    unitSellingPrice: 300,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Proton pump inhibitor for GERD, gastric and duodenal ulcers, and acid reflux.',
    synced: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-010',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin Hydrochloride',
    sku: 'CIP-500',
    barcode: '8904445556667',
    category: 'Antibiotics',
    dosageForm: 'tablets',
    packSize: 10,
    unitName: 'Tablet',
    reorderThreshold: 15,
    buyingPrice: 3500,
    sellingPrice: 6000,
    unitSellingPrice: 700,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Fluoroquinolone antibiotic for urinary tract infections, typhoid, and enteric infections.',
    synced: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Benylin 4-Flu Syrup 100ml',
    genericName: 'Diphenhydramine + Pseudoephedrine + Paracetamol',
    sku: 'BEN-4FLU-100',
    barcode: '6001004001111',
    category: 'Cough & Cold',
    dosageForm: 'syrup',
    packSize: 1,
    unitName: 'Bottle (100ml)',
    reorderThreshold: 8,
    buyingPrice: 7500,
    sellingPrice: 11000,
    unitSellingPrice: 11000,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Multi-symptom relief from head cold, nasal congestion, fever, and dry cough.',
    synced: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Ceftriaxone 1g Injection Vial',
    genericName: 'Ceftriaxone Sodium',
    sku: 'CEF-1G-INJ',
    barcode: '8905556667778',
    category: 'Antibiotics',
    dosageForm: 'vials',
    packSize: 10,
    unitName: 'Vial',
    reorderThreshold: 10,
    buyingPrice: 28000,
    sellingPrice: 42000,
    unitSellingPrice: 4500,
    isPom: true,
    requiresStorageWarning: false,
    description: 'Third-generation cephalosporin for severe hospital/community bacterial infections.',
    synced: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Oral Rehydration Salts (ORS)',
    genericName: 'WHO Formula Glucose Electrolytes',
    sku: 'ORS-WHO-SACH',
    barcode: '8906667778889',
    category: 'Pediatric & Dehydration',
    dosageForm: 'powder',
    packSize: 50,
    unitName: 'Sachet',
    reorderThreshold: 25,
    buyingPrice: 12000,
    sellingPrice: 18000,
    unitSellingPrice: 500,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Essential electrolyte replacer for acute diarrhea, vomiting, and pediatric dehydration.',
    synced: true,
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Hydrocortisone 1% Cream 15g',
    genericName: 'Hydrocortisone Acetate',
    sku: 'HYD-CRM-15G',
    barcode: '5019998887776',
    category: 'Dermatology',
    dosageForm: 'cream',
    packSize: 1,
    unitName: 'Tube (15g)',
    reorderThreshold: 6,
    buyingPrice: 3500,
    sellingPrice: 5500,
    unitSellingPrice: 5500,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Mild topical corticosteroid for eczema, dermatitis, and insect bite irritation.',
    synced: true,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-015',
    tenantId: 'demo-tenant-pharmpulse',
    name: 'Multivitamin + Zinc Syrup 200ml',
    genericName: 'Vitamins A, B-Complex, C, D3, E + Zinc',
    sku: 'VIT-ZNC-200ML',
    barcode: '6002223334445',
    category: 'Vitamins & Supplements',
    dosageForm: 'syrup',
    packSize: 1,
    unitName: 'Bottle (200ml)',
    reorderThreshold: 10,
    buyingPrice: 6000,
    sellingPrice: 9500,
    unitSellingPrice: 9500,
    isPom: false,
    requiresStorageWarning: false,
    description: 'Immune booster and growth tonic for children and convalescing adults.',
    synced: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Helper to calculate target dates relative to today
const getFutureDate = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const INITIAL_BATCHES: Batch[] = [
  // Augmentin 625mg (2 batches: one soon to expire to test FEFO)
  {
    id: 'batch-aug-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-001',
    batchNumber: 'AUG-B2401',
    expiryDate: getFutureDate(24), // Expiring in 24 days! (Orange Alert)
    quantity: 6,
    costPrice: 18000,
    supplier: 'GlaxoSmithKline Healthcare Ltd',
    synced: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'batch-aug-02',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-001',
    batchNumber: 'AUG-B2409',
    expiryDate: getFutureDate(420), // Fresh batch
    quantity: 24,
    costPrice: 18000,
    supplier: 'GlaxoSmithKline Healthcare Ltd',
    synced: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Panadol Extra (2 batches: one expired to showcase Red warning)
  {
    id: 'batch-pan-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-002',
    batchNumber: 'PAN-EX-230',
    expiryDate: getFutureDate(-12), // Expired 12 days ago! (Red Alert)
    quantity: 2,
    costPrice: 15000,
    supplier: 'Haleon Consumer Health',
    synced: true,
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'batch-pan-02',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-002',
    batchNumber: 'PAN-EX-245',
    expiryDate: getFutureDate(510),
    quantity: 45,
    costPrice: 15000,
    supplier: 'Haleon Consumer Health',
    synced: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Coartem (2 batches: one expiring in 75 days (Yellow Alert))
  {
    id: 'batch-coa-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-003',
    batchNumber: 'COA-8812',
    expiryDate: getFutureDate(75), // Expiring in 75 days (Yellow Alert)
    quantity: 14,
    costPrice: 8500,
    supplier: 'Novartis Pharma AG',
    synced: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'batch-coa-02',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-003',
    batchNumber: 'COA-9104',
    expiryDate: getFutureDate(620),
    quantity: 35,
    costPrice: 8500,
    supplier: 'Novartis Pharma AG',
    synced: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Azithromycin
  {
    id: 'batch-azi-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-004',
    batchNumber: 'AZI-K331',
    expiryDate: getFutureDate(280),
    quantity: 32,
    costPrice: 4500,
    supplier: 'Cipla Global Limited',
    synced: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Metformin (Low stock demo: only 4 packs, below threshold 10)
  {
    id: 'batch-met-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-005',
    batchNumber: 'MET-4491',
    expiryDate: getFutureDate(360),
    quantity: 4, // Low stock!
    costPrice: 7000,
    supplier: 'Dawa Pharmaceuticals',
    synced: true,
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Amlodipine
  {
    id: 'batch-aml-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-006',
    batchNumber: 'AML-9022',
    expiryDate: getFutureDate(310),
    quantity: 18,
    costPrice: 5000,
    supplier: 'Pfizer East Africa',
    synced: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Cataflam
  {
    id: 'batch-cat-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-007',
    batchNumber: 'CAT-5501',
    expiryDate: getFutureDate(440),
    quantity: 22,
    costPrice: 9000,
    supplier: 'Novartis Consumer Health',
    synced: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Ventolin Inhaler (Low stock demo: only 3 canisters, threshold 5)
  {
    id: 'batch-ven-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-008',
    batchNumber: 'VEN-IN-89',
    expiryDate: getFutureDate(190),
    quantity: 3, // Low stock!
    costPrice: 11000,
    supplier: 'GlaxoSmithKline Healthcare Ltd',
    synced: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Omeprazole
  {
    id: 'batch-ome-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-009',
    batchNumber: 'OME-7714',
    expiryDate: getFutureDate(270),
    quantity: 26,
    costPrice: 4000,
    supplier: 'AstraZeneca UK',
    synced: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Ciprofloxacin
  {
    id: 'batch-cip-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-010',
    batchNumber: 'CIP-2390',
    expiryDate: getFutureDate(340),
    quantity: 25,
    costPrice: 3500,
    supplier: 'Bayer Healthcare',
    synced: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Benylin 4-Flu
  {
    id: 'batch-ben-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-011',
    batchNumber: 'BEN-4F-11',
    expiryDate: getFutureDate(180),
    quantity: 16,
    costPrice: 7500,
    supplier: 'Johnson & Johnson Consumer',
    synced: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Ceftriaxone Injection
  {
    id: 'batch-cef-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-012',
    batchNumber: 'CEF-TX-99',
    expiryDate: getFutureDate(400),
    quantity: 15,
    costPrice: 28000,
    supplier: 'Roche Pharma',
    synced: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ORS Sachets
  {
    id: 'batch-ors-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-013',
    batchNumber: 'ORS-WH-02',
    expiryDate: getFutureDate(520),
    quantity: 80,
    costPrice: 12000,
    supplier: 'Shelys Pharmaceuticals Ltd',
    synced: true,
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Hydrocortisone Cream
  {
    id: 'batch-hyd-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-014',
    batchNumber: 'HYD-CR-73',
    expiryDate: getFutureDate(210),
    quantity: 14,
    costPrice: 3500,
    supplier: 'Galderma Labs',
    synced: true,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Multivitamin Syrup
  {
    id: 'batch-vit-01',
    tenantId: 'demo-tenant-pharmpulse',
    productId: 'prod-015',
    batchNumber: 'VIT-ZC-50',
    expiryDate: getFutureDate(300),
    quantity: 20,
    costPrice: 6000,
    supplier: 'Vitabiotics Ltd',
    synced: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Sample past sales for realistic charts and metrics immediately upon startup
export const INITIAL_SALES: { sale: Sale; items: SaleItem[] }[] = [
  {
    sale: {
      id: 'sale-demo-001',
      tenantId: 'demo-tenant-pharmpulse',
      receiptNumber: 'REC-20261004-001',
      itemsCount: 2,
      subtotal: 39500,
      discount: 0,
      tax: 0,
      total: 39500,
      costOfGoods: 26500,
      profit: 13000,
      paymentMethod: 'mobile_money',
      paymentDetails: {
        mobileMoney: {
          provider: 'mpesa',
          phoneNumber: '0754123456',
          transactionRef: 'QJ78KL9201',
        },
      },
      amountPaid: 39500,
      changeGiven: 0,
      attendantName: 'Pharm. David Ndunguru',
      patientName: 'Grace Makau',
      doctorName: 'Dr. J. Mwita (Aga Khan Hospital)',
      hasPomItems: true,
      status: 'completed',
      synced: true,
      created_at: new Date(Date.now() - 4 * 3600000).toISOString(), // 4 hours ago
      updated_at: new Date().toISOString(),
    },
    items: [
      {
        id: 'si-001-1',
        tenantId: 'demo-tenant-pharmpulse',
        saleId: 'sale-demo-001',
        productId: 'prod-001',
        batchId: 'batch-aug-01',
        productName: 'Augmentin 625mg',
        genericName: 'Amoxicillin + Clavulanic Acid',
        dosageForm: 'tablets',
        batchNumber: 'AUG-B2401',
        expiryDate: getFutureDate(24),
        unitType: 'pack',
        quantity: 1,
        unitPrice: 26000,
        costPrice: 18000,
        discount: 0,
        totalPrice: 26000,
        synced: true,
        created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
      },
      {
        id: 'si-001-2',
        tenantId: 'demo-tenant-pharmpulse',
        saleId: 'sale-demo-001',
        productId: 'prod-003',
        batchId: 'batch-coa-01',
        productName: 'Coartem 20/120mg (6x4)',
        genericName: 'Artemether + Lumefantrine',
        dosageForm: 'tablets',
        batchNumber: 'COA-8812',
        expiryDate: getFutureDate(75),
        unitType: 'pack',
        quantity: 1,
        unitPrice: 13500,
        costPrice: 8500,
        discount: 0,
        totalPrice: 13500,
        synced: true,
        created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
      },
    ],
  },
  {
    sale: {
      id: 'sale-demo-002',
      tenantId: 'demo-tenant-pharmpulse',
      receiptNumber: 'REC-20261004-002',
      itemsCount: 1,
      subtotal: 16500,
      discount: 0,
      tax: 0,
      total: 16500,
      costOfGoods: 11000,
      profit: 5500,
      paymentMethod: 'cash',
      paymentDetails: {
        cashReceived: 20000,
        changeGiven: 3500,
      },
      amountPaid: 20000,
      changeGiven: 3500,
      attendantName: 'Sarah Kavishe (Dispenser)',
      patientName: 'Kassim Bakari',
      doctorName: 'Dr. F. Temu',
      hasPomItems: true,
      status: 'completed',
      synced: true,
      created_at: new Date(Date.now() - 2.5 * 3600000).toISOString(), // 2.5 hours ago
      updated_at: new Date().toISOString(),
    },
    items: [
      {
        id: 'si-002-1',
        tenantId: 'demo-tenant-pharmpulse',
        saleId: 'sale-demo-002',
        productId: 'prod-008',
        batchId: 'batch-ven-01',
        productName: 'Ventolin Inhaler 100mcg',
        genericName: 'Salbutamol Sulfate',
        dosageForm: 'inhaler',
        batchNumber: 'VEN-IN-89',
        expiryDate: getFutureDate(190),
        unitType: 'pack',
        quantity: 1,
        unitPrice: 16500,
        costPrice: 11000,
        discount: 0,
        totalPrice: 16500,
        synced: true,
        created_at: new Date(Date.now() - 2.5 * 3600000).toISOString(),
      },
    ],
  },
  {
    sale: {
      id: 'sale-demo-003',
      tenantId: 'demo-tenant-pharmpulse',
      receiptNumber: 'REC-20261004-003',
      itemsCount: 3,
      subtotal: 25000,
      discount: 1000,
      tax: 0,
      total: 24000,
      costOfGoods: 14500,
      profit: 9500,
      paymentMethod: 'card',
      paymentDetails: {
        card: {
          cardType: 'visa',
          last4: '4892',
          authCode: 'APPR-88102',
        },
      },
      amountPaid: 24000,
      changeGiven: 0,
      attendantName: 'Pharm. David Ndunguru',
      patientName: 'Fatma Rashid',
      hasPomItems: false,
      status: 'completed',
      synced: true,
      created_at: new Date(Date.now() - 1 * 3600000).toISOString(), // 1 hour ago
      updated_at: new Date().toISOString(),
    },
    items: [
      {
        id: 'si-003-1',
        tenantId: 'demo-tenant-pharmpulse',
        saleId: 'sale-demo-003',
        productId: 'prod-007',
        batchId: 'batch-cat-01',
        productName: 'Cataflam 50mg',
        genericName: 'Diclofenac Potassium',
        dosageForm: 'tablets',
        batchNumber: 'CAT-5501',
        expiryDate: getFutureDate(440),
        unitType: 'pack',
        quantity: 1,
        unitPrice: 14000,
        costPrice: 9000,
        discount: 0,
        totalPrice: 14000,
        synced: true,
        created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
      },
      {
        id: 'si-003-2',
        tenantId: 'demo-tenant-pharmpulse',
        saleId: 'sale-demo-003',
        productId: 'prod-011',
        batchId: 'batch-ben-01',
        productName: 'Benylin 4-Flu Syrup 100ml',
        genericName: 'Diphenhydramine + Pseudoephedrine + Paracetamol',
        dosageForm: 'syrup',
        batchNumber: 'BEN-4F-11',
        expiryDate: getFutureDate(180),
        unitType: 'pack',
        quantity: 1,
        unitPrice: 11000,
        costPrice: 7500,
        discount: 1000,
        totalPrice: 10000,
        synced: true,
        created_at: new Date(Date.now() - 1 * 3600000).toISOString(),
      },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    tenantId: 'demo-tenant-pharmpulse',
    action: 'STORE_ACTIVATED',
    category: 'license',
    details: 'Store activated successfully under license key PHARM-2026-ALPHA-9921',
    attendantName: 'Pharm. David Ndunguru',
    synced: true,
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: 'audit-002',
    tenantId: 'demo-tenant-pharmpulse',
    action: 'INVENTORY_IMPORT',
    category: 'inventory',
    details: 'Initial formulary seeded with 15 essential therapeutic categories',
    attendantName: 'Pharm. David Ndunguru',
    synced: true,
    created_at: new Date(Date.now() - 47 * 3600000).toISOString(),
  },
  {
    id: 'audit-003',
    tenantId: 'demo-tenant-pharmpulse',
    action: 'SALE_COMPLETED',
    category: 'pos',
    details: 'Completed sale REC-20261004-001 via M-Pesa (TSh 39,500)',
    attendantName: 'Pharm. David Ndunguru',
    synced: true,
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'audit-004',
    tenantId: 'demo-tenant-pharmpulse',
    action: 'SALE_COMPLETED',
    category: 'pos',
    details: 'Completed sale REC-20261004-002 via Cash (TSh 16,500)',
    attendantName: 'Sarah Kavishe (Dispenser)',
    synced: true,
    created_at: new Date(Date.now() - 2.5 * 3600000).toISOString(),
  },
];
